name: Run Tests
on: push

jobs:
  find-specs:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.get-files.outputs.files }}
    steps:
     - uses: actions/checkout@v2
     - id: get-files
       run: |
        npm ci
        echo "::set-output name=files::$(node get_spec.js)"

  run-tests:
    runs-on: ubuntu-latest
    needs: find-specs
    container: cypress/browsers:node14.19.0-chrome100-ff99-edge
    strategy:
      matrix:
        browser: [chrome, electron, edge]
        spec: ${{ fromJSON(needs.find-specs.outputs.files) }}
    steps:
      - uses: actions/checkout@v2

      - run: |
          npm ci
          npm run cy:run:${{ matrix.browser }} -- --spec ${{ matrix.spec }}

      - uses: actions/upload-artifact@v2
        with:
          name: reports
          path: junit/*.xml


  generate-reports:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: reports

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: ./*.xml