name: Run Tests
on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  run-tests:
   runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        # normally you would write
        # uses: cypress-io/github-action@v2
        uses: ./
        # the parameters below are only necessary
        # because we are running these examples in a monorepo
        with:
          working-directory: '*integration/Weather.spec.js'
          # just for full picture after installing Cypress
          # print information about detected browsers, etc
          # see https://on.cypress.io/command-line#cypress-info
          build: npx cypress info