# This is a basic workflow to help you get started with Actions

name: Run test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


jobs:
  run-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.17.0-chrome91-ff89
    strategy:
      matrix:
        browser: [chrome, electron]
    steps:
      - uses: actions/checkout@v2

      - run: |
          npm i
          npm run cy:run:${{ matrix.browser }}

      - uses: actions/upload-artifact@v2
        with:
          name: reports
          path: junit/*.xml


  generate-reports:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: reports

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: ./*.xml
